version: '3'
services:
  nest:
    container_name: nest
    build: .
    ports:
      - 3000:3000
    volumes: 
      - .:/app
      - /app/node_modules
    networks:
      - docker-network
    depends_on:
      - postgres
  postgres:
    container_name: banco
    image: 'postgres:13-alpine'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: 'test'
      POSTGRES_PASSWORD: 'test'
      POSTGRES_DB: 'test'
    networks:
      - docker-network
networks:
  docker-network:
